language: ruby
rvm:
  - 1.9.3
env:
  global:
    - secure: "gpvQKUMaDkVArpAJjkEN0eNzwjhqGR8HLga9moD+g3og2s/Tl8EtS56vvX1w\nFB5VidCYRRAfSB1MWWxTybj8HSC+LWtuHKNkVQSZLBdAdoCI4PhSBBh0Yokl\nAVuZewGbp0zBhKPtZJ7ifT0xZ1ID9kFdeyDJabuFuCnHbVoPb8c="
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database wts_test' -U postgres
after_script:
  - gem install heroku
  - git remote add heroku git@heroku.com:rails3-tutorial-2nd.git
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:clear
  - yes | heroku keys:add
  - yes | git push heroku master